# Base image
FROM node:14

# Set working directory
WORKDIR /usr/src/app

# Copy package files
COPY package.json ./
COPY package-lock.json ./

# Clear npm cache and install dependencies
RUN npm cache clean --force && npm install --legacy-peer-deps

# Copy app files
COPY . .

# Build the app
RUN npm run build

# Install serve to serve the build folder
RUN npm install -g serve

# Set the command to start the app
CMD ["serve", "-s", "build"]

# Expose the port the app runs on
EXPOSE 3000
